### ISSUE TITLE
POC vulnerable app not detected

### ISSUE THREAD

**Issue by calebTree** [fullhunt/log4j-scan#103]
I ran the docker image from this GitHub POC repo [https://github.com/kozmer/log4j-shell-poc](https://github.com/kozmer/log4j-shell-poc) yet the script reports "not vulnerable". I was able to get the reverse shell using the steps in the POC ReadMe so my understanding is it must be vulnerable?

**Comment by mazen160** [comment]
The reason is, the parameter word list is generic, and the name used on the words is not listed there. 

https://github.com/kozmer/log4j-shell-poc/blob/a378616de6786e70f6f071e79260430d5df59340/vulnerable-application/src/main/java/com/example/log4shell/LoginServlet.java#L19

Post parameter: `uname`

I added this parameter to the log4j-scan
```
python3 log4j-scan.py -u http://127.0.0.1:8080/login --run-all-tests
```
