### ISSUE TITLE
please check your logs to verify the existence of the vulnerability

### ISSUE THREAD

**Issue by sarah026** [fullhunt/log4j-scan#98]
Hi

The scan says 
"[•] Payloads sent to all URLs. Custom DNS Callback host is provided, please check your logs to verify the existence of the vulnerability. Exiting."

What logs is it referring to here? The application itself? or the DNS server?
Thanks

**Comment by axel3rd** [comment]
Hi,

In case of *Custom DNS Callback host* usage, this tool cannot (by design) request custom DNS server to check if a request has been done by a vulnerable application (contrary to [interact.sh pull usage](https://github.com/fullhunt/log4j-scan/blob/master/log4j-scan.py#L228-L236)) => you have to check your DNS server manually.
This is the sens if this sentence IMO (but you can check application logs too 😁).

**Comment by mazen160** [comment]
As @axel3rd stated, this logs is related to the DNS logs of the custom DNS server you're using :)
